//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_retail_pd
    {
        public int id { get; set; }
        public string bucket { get; set; }
        public Nullable<double> pd { get; set; }
        public Nullable<double> asset_corelation { get; set; }
        public Nullable<double> @base { get; set; }
        public Nullable<double> best { get; set; }
        public Nullable<double> worst { get; set; }
    }
}
