//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprehensive_Report
    {
        public int Id { get; set; }
        public string Facility_Id { get; set; }
        public string Portfolio { get; set; }
        public string SubPortfolio { get; set; }
        public Nullable<System.DateTime> Valuation_date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<int> Payment_Frequency { get; set; }
        public Nullable<double> Interest_Rate { get; set; }
        public Nullable<double> EAD { get; set; }
        public Nullable<double> Starting_Exposure { get; set; }
        public Nullable<double> Discount_Rate { get; set; }
        public Nullable<double> PD_12_M_Base { get; set; }
        public Nullable<double> PD_12_M_Best { get; set; }
        public Nullable<double> PD_12_M_Worst { get; set; }
        public Nullable<double> LGD { get; set; }
        public Nullable<double> LECL_Base { get; set; }
        public Nullable<double> LECL_Best { get; set; }
        public Nullable<double> LECL_Worst { get; set; }
        public Nullable<double> ECL_12_M_Base { get; set; }
        public Nullable<double> ECL_12_M_Best { get; set; }
        public Nullable<double> ECL_12_M_Worst { get; set; }
        public Nullable<double> Stage { get; set; }
        public Nullable<double> IFRS9_ECL_Base_Number { get; set; }
        public Nullable<double> IFRS9_ECL_Best_Number { get; set; }
        public Nullable<double> FRS9_ECLWorst_Number { get; set; }
        public string by_user { get; set; }
    }
}
