//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECL_GeneralInput
    {
        public System.DateTime AssessmentDate { get; set; }
        public string DataImportID { get; set; }
        public System.DateTime ExtractDate { get; set; }
        public string FacilityID { get; set; }
        public string CustomerID { get; set; }
        public string PortFolioCode { get; set; }
        public string SubPortFolioCode { get; set; }
        public string ProductCode { get; set; }
        public Nullable<byte> InfoFlag { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> OriginationDate { get; set; }
        public Nullable<System.DateTime> FirstInstallmentDate { get; set; }
        public Nullable<int> PastDueDays { get; set; }
        public Nullable<int> OriginalRating { get; set; }
        public Nullable<int> CurrentRating { get; set; }
        public Nullable<int> Transition { get; set; }
        public Nullable<double> BasePD { get; set; }
        public Nullable<double> PositivePDBest { get; set; }
        public Nullable<double> NegativePDWorst { get; set; }
        public Nullable<double> LGDRate { get; set; }
        public Nullable<double> Limit { get; set; }
        public Nullable<double> DrawnAmount { get; set; }
        public Nullable<double> UnDrawnAmount { get; set; }
        public Nullable<double> InterestAccrued { get; set; }
        public Nullable<double> CCF { get; set; }
        public Nullable<double> EAD { get; set; }
        public Nullable<double> ImpairmentAmount { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public double EIR { get; set; }
        public double ContractualRate { get; set; }
        public int PaymentFrequency { get; set; }
        public Nullable<short> Stage { get; set; }
        public string StageReason { get; set; }
        public Nullable<double> NominalInterestRate { get; set; }
        public Nullable<short> PaymentTypeID { get; set; }
        public string MadificationFlag { get; set; }
        public Nullable<double> ModificationValue { get; set; }
        public Nullable<byte> WrittenOffFlag { get; set; }
        public Nullable<double> WrittenOffValue { get; set; }
        public byte IsDefault { get; set; }
        public string Clasification { get; set; }
        public Nullable<byte> IsWatchlist { get; set; }
        public Nullable<byte> IsInsolvency { get; set; }
        public Nullable<byte> HighRiskindustry { get; set; }
        public Nullable<byte> Anyotherflag { get; set; }
        public Nullable<byte> DPDflag30 { get; set; }
        public Nullable<byte> DPDflag60 { get; set; }
        public Nullable<byte> DPD_flag { get; set; }
        public Nullable<byte> AdditionalFlag { get; set; }
        public Nullable<byte> AdditionalFlag1 { get; set; }
        public Nullable<byte> TransitionCheck { get; set; }
        public Nullable<double> CollateralValue { get; set; }
        public string CollateralDescription { get; set; }
        public double Haircut { get; set; }
        public Nullable<byte> CollateralBenefit { get; set; }
        public Nullable<double> EAD_Total { get; set; }
        public string Rated { get; set; }
        public Nullable<byte> IsRestructured { get; set; }
        public Nullable<byte> AdditionalFlag2 { get; set; }
        public string Funded { get; set; }
        public Nullable<int> GOP { get; set; }
        public string by_user { get; set; }
        public string Acceptance { get; set; }
        public string External_Ratings { get; set; }
        public Nullable<byte> FVOCI_flag { get; set; }
    }
}
