//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForwordLooking_PD
    {
        public int id { get; set; }
        public string Portfolio { get; set; }
        public Nullable<int> Ratings { get; set; }
        public Nullable<double> TTC { get; set; }
        public Nullable<double> Assest_Correlation { get; set; }
        public Nullable<double> Base { get; set; }
        public Nullable<double> Best { get; set; }
        public Nullable<double> Worst { get; set; }
        public string mac_variable { get; set; }
        public string by_user { get; set; }
    }
}
