//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForwordFile
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> Year { get; set; }
        public string MacroEconimcal { get; set; }
        public Nullable<double> ValueData { get; set; }
        public string by_user { get; set; }
    }
}
