//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGD_Output
    {
        public int id { get; set; }
        public string AccountNo { get; set; }
        public string Segment { get; set; }
        public string IndustrySegment { get; set; }
        public System.DateTime NPADate { get; set; }
        public string NPAQuarter { get; set; }
        public double Balance { get; set; }
        public double HistoricalRecovery { get; set; }
        public double HistoricalCost { get; set; }
        public double HistoricalLGD { get; set; }
        public double EconomicRecovery { get; set; }
        public double EconomicCost { get; set; }
        public double EconomicLGD { get; set; }
        public string by_user { get; set; }
    }
}
