//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGD_General_Input
    {
        public int id { get; set; }
        public string FacilityID { get; set; }
        public string CustomerID { get; set; }
        public string AccountNO { get; set; }
        public System.DateTime NPADate { get; set; }
        public double Balance { get; set; }
        public double InterestRate { get; set; }
        public string Segment { get; set; }
        public System.DateTime AssessmentDate { get; set; }
        public string by_user { get; set; }
    }
}
