//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_log
    {
        public int Id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public string session_id { get; set; }
        public Nullable<int> login_count { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    }
}
