<table class="table table-bordered table-striped ajax_view hide-footer dataTable table-styling table-hover table-primary" id="purchase_table" style="width: 100%;">
    <thead>
        <tr>
            <th>@lang('messages.action')</th>
            <th>@lang('messages.date')</th>
            <th>Transaction No</th>
            <th>Purchase Order No</th> 
            <th>Purchase Type</th>
            <th>Product Type</th>
            <th>Supplier Name</th>
            <th>Transporter</th>
            <th>Vehicle No</th>
            <th>Sales Man</th>
            <th>Generated BY</th>
            <th>@lang('purchase.location')</th>
        </tr>
    </thead>
  
</table>